import type { NextPage } from 'next'
import Head from 'next/head'
import data from '../local/data.json';
import translations from '../local/translations.json';
import Header from '../components/header'
import { RecruiteeList } from '../components/RecruiteeList';

const Home: NextPage = () => {
	const { recruitees } = data;

	return (
		<div>
			<Head>
			<title>Crowd Collective</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="Layout_main">
				<div className="sections">
					<section className="section-1">
						<h1 className="section-heading">{translations.sectionHeading}</h1>
						<p className="section-description">{translations.sectionDescription}</p>
					</section>
					<section className="section-2">
						<RecruiteeList recruitees={recruitees} />
					</section>
				</div>
			</div>
		</div>
	)
}

export default Home
