import type { NextPage } from 'next'
import Head from 'next/head'
import data from '../local/data.json';
import Header from '../components/header'
import { RecruiteeList } from '../components/RecruiteeList';

const Home: NextPage = () => {
	const { recruitees } = data;

	return (
		<div>
			<Head>
			<title>Crowd Collective</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="Layout_main">
				<div className="sections">
					<RecruiteeList recruitees={recruitees} />
				</div>
			</div>
		</div>
	)
}

export default Home
